INSERT INTO time (NOME) VALUES ('INTER');
INSERT INTO time (NOME) VALUES ('GREMIO');


INSERT INTO avaliador (NOME, EMAIL) VALUES ('Ana Paula', 'anapaula@pucrs.br');
INSERT INTO avaliador (NOME, EMAIL) VALUES ('Cassio', 'cassio@pucrs.br');
INSERT INTO avaliador (NOME, EMAIL) VALUES ('Gabriel Correa', 'binhosckina@gmail.com');


INSERT INTO ALUNO (NOME, CURSO, TIME_ID) values ('alessandro','Engenharia de Software',  1);
INSERT INTO ALUNO (NOME, CURSO, TIME_ID) values ('Chiara','Engenharia de Software',  2);
INSERT INTO ALUNO (NOME, CURSO, TIME_ID) values ('Edson','Engenharia de Software',  1);
INSERT INTO ALUNO (NOME, CURSO, TIME_ID) values ('Gabriel','Engenharia de Software',  1);
INSERT INTO ALUNO (NOME, CURSO, TIME_ID) values ('João','Engenharia de Software',  2);
INSERT INTO ALUNO (NOME, CURSO, TIME_ID) values ('Ciclano','Medicina', null);
INSERT INTO ALUNO (NOME, CURSO, TIME_ID) values ('Beltrano','Odontologia', null);
INSERT INTO ALUNO (NOME, CURSO, TIME_ID) values ('Fulano','Piscologia', null);


INSERT INTO AVALIACAO (SOFTWARE_FUNCIONANDO, PROCESSO, PICTCH, INOVACAO, FORMACAO_TIME, AVALIADOR_MODEL_ID, TIME_MODEL_ID) VALUES (5,4,3,4,5,1,1);
INSERT INTO AVALIACAO (SOFTWARE_FUNCIONANDO, PROCESSO, PICTCH, INOVACAO, FORMACAO_TIME, AVALIADOR_MODEL_ID, TIME_MODEL_ID) VALUES (2,1,4,2,3,1,2);
INSERT INTO AVALIACAO (SOFTWARE_FUNCIONANDO, PROCESSO, PICTCH, INOVACAO, FORMACAO_TIME, AVALIADOR_MODEL_ID, TIME_MODEL_ID) VALUES (1,2,3,4,5,2,1);
INSERT INTO AVALIACAO (SOFTWARE_FUNCIONANDO, PROCESSO, PICTCH, INOVACAO, FORMACAO_TIME, AVALIADOR_MODEL_ID, TIME_MODEL_ID) VALUES (0,1,1,2,3,2,2);